apiVersion: apps/v1
kind: Deployment
metadata:
  name: echarging
  labels:
    app: echarging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echarging
  template:
    metadata:
      labels:
        app: echarging
    spec:
      containers:
        - name: echarging
          image: username/echarging:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5